# This is a basic workflow to help you get started with Actions

name: DiscordIssues

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [opened, closed]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  post_discord:
    runs-on: ubuntu-latest
    name: Post issue status to discord
    steps:
      - uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
